LibraryApp/Models/Book.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryApp.Models
{
	public class Book
	{
		// ID книги
		public int Id { get; set; }
		// Название книги
		public string Name { get; set; }
		// Автор книги
		public string Author { get; set; }
		// Описание книги
		public string Description { get; set; }
		//Выдана книга или доступна
		public bool IsAvailable { get; set; }
		//Id клиента, который арендует книгу
		public int ClientId { get; set; }
	}
}

LibraryApp/Models/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace LibraryApp.Models
{
	public class Client
	{
		// ID клиента
		public int Id { get; set; }
		// Имя клиента
		public string Name { get; set; }
		//Почта клиента
		public string Email { get; set; }
	}
}

LibraryApp/Controllers/BookController.cs
using LibraryApp.Models;
using LibraryApp.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryApp.Controllers
{
    public class BookController : Controller
    {
		private readonly IBookModelRepository _bookModelRepository;

		public BookController(IBookModelRepository bookModelRepository)
		{
			_bookModelRepository = bookModelRepository;
		}

		public ActionResult Index()
        {
            return View();
        }

		public ActionResult AddBook()
		{
			return View();
		}

		[HttpPost]
		public JsonResult AddBook(Book model)
		{
			if (ModelState.IsValid)
			{
				_bookModelRepository.AddBook(model);
				return Json(new { success = true });
			}
			return Json(new { success = false, message = "Некорректные данные" });
		}
	}
}

LibraryApp/Controllers/ClientController.cs
using LibraryApp.Models;
using LibraryApp.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryApp.Controllers
{
    public class ClientController : Controller
    {
		private readonly IClientModelRepository _clientModelRepository;

		public ClientController(IClientModelRepository clientModelRepository)
		{
			_clientModelRepository = clientModelRepository;
		}
		public ActionResult Index()
        {
            return View();
        }

		public ActionResult AddClient()
		{
			return View();
		}

		[HttpGet]
		public JsonResult GetClients()
		{
			var books = _clientModelRepository.GetAllClients();
			return Json(books, JsonRequestBehavior.AllowGet);
		}

		[HttpPost]
		public JsonResult AddClient(Client model)
		{
			if (ModelState.IsValid)
			{
				var isMailExist = _clientModelRepository.IsEmailExists(model.Email);

				if (!isMailExist)
				{
					_clientModelRepository.AddClient(model);
					return Json(new { success = true });
				}
				else
				{
					return Json(new { success = false, message = "Такого Email уже существует!" });
				}
			}
			return Json(new { success = false, message = "Некорректные данные" });
		}
	}
}

LibraryApp/Controllers/HomeController.cs
using LibraryApp.Models;
using LibraryApp.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LibraryApp.Controllers
{
	public class HomeController : Controller
	{
		private readonly IBookModelRepository _bookModelRepository;
		private readonly IClientModelRepository _clientModelRepository;

		public HomeController(IBookModelRepository bookModelRepository, IClientModelRepository clientModelRepository)
		{
			_bookModelRepository = bookModelRepository;
			_clientModelRepository = clientModelRepository;
		}

		public ActionResult Index()
		{
			var books = _bookModelRepository.GetAllBooks();
			return View(books);
		}

		[HttpGet]
		public JsonResult GetBooks()
		{
			var books = _bookModelRepository.GetAllBooks();
			return Json(books, JsonRequestBehavior.AllowGet);
		}
		

		[HttpPost]
		public JsonResult UpdateBookDescription(int id, string description)
		{
			try
			{
				_bookModelRepository.UpdateBookDescription(id, description);
				return Json(new { success = true });
			}
			catch (Exception ex)
			{
				return Json(new { success = false, message = ex.Message });
			}
		}

		[HttpPost]
		public ActionResult RentOrReturnBook(int bookId, string clientEmail, bool isAvailable)
		{
			try
			{
				if (isAvailable)
				{
					var isMailExist = _clientModelRepository.IsEmailExists(clientEmail);

					if (isMailExist)
					{
						// Если книга доступна, арендуем её
						_bookModelRepository.RentBook(bookId, clientEmail);
					}
					else
					{
						return Json(new { success = false, message = "Такого Email не существует!" });
					}
					
				}
				else
				{
					// Если книга уже арендована, возвращаем её
					_bookModelRepository.ReturnBook(bookId);
				}
				return Json(new { success = true, isAvailable = !isAvailable });
			}
			catch (Exception ex)
			{
				return Json(new { success = false, message = ex.Message });
			}
		}
	}
}

LibraryApp/Views/Book/AddBook.cshtml
@model LibraryApp.Models.Book

@{
    ViewBag.Title = "Добавить книгу";
}

<!DOCTYPE html>
<html>
<head>
	<title>Добавить книгу</title>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
        $(document).ready(function() {
            $('#createBookForm').submit(function(event) {
                event.preventDefault();

                var bookData = {
                    Name: $('#Name').val(),
                    Author: $('#Author').val(),
                    Description: $('#Description').val()
                };

                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify(bookData),
                    success: function(response) {
                        alert("Книга добавлена успешно!");
                        // Очистка формы после успешного добавления книги
                        $('#createBookForm')[0].reset();
                    },
                    error: function(xhr, status, error) {
                        console.error(error);
                        alert("При добавлении книги произошла ошибка!");
                    }
                });
            });
        });
	</script>
</head>
<body>
	<h2>Добавить книгу</h2>

	<form id="createBookForm">
		<div class="form-group">
			<label for="Name">Название книги</label>
			<input type="text" id="Name" name="Name" class="form-control" />
		</div>
		<div class="form-group">
			<label for="Author">Автор</label>
			<input type="text" id="Author" name="Author" class="form-control" />
		</div>
		<div class="form-group">
			<label for="Description">Описание</label>
			<input type="text" id="Description" name="Description" class="form-control" />
		</div>
		<div>
			<button type="submit" class="btn btn-primary">Добавить книгу</button>
		</div>
	</form>
</body>
</html>

LibraryApp/Views/Client/AddClient.cshtml
@model LibraryApp.Models.Client

@{
	ViewBag.Title = "Добавить клиента";
}

<!DOCTYPE html>
<html>
<head>
	<title>Добавить клиента</title>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
        $(document).ready(function() {
            $('#addClientForm').submit(function(event) {
                event.preventDefault();

                var clientData = {
                    Name: $('#Name').val(),
                    Email: $('#Email').val()
                };

                $.ajax({
                    type: 'POST',
                    contentType: 'application/json',
                    data: JSON.stringify(clientData),
                    success: function (response) {
						if (response.success) {
							alert("Клиент успешно добавлен!");
							$('#addClientForm')[0].reset();
						} else {
							alert("Ошибка: " + response.message);
						}
                    },
                    error: function(xhr, status, error) {
                        console.error(error);
                        alert("При создании клиента произошла ошибка!");
                    }
                });
            });
        });
	</script>
</head>
<body>
	<h2>Добавить клиента</h2>

	<form id="addClientForm">
		<div class="form-group">
			<label for="Name">Имя клиента</label>
			<input type="text" id="Name" name="Name" class="form-control" />
		</div>
		<div class="form-group">
			<label for="Email">Email</label>
			<input type="text" id="Email" name="Email" class="form-control" />
		</div>
		<button type="submit" class="btn btn-primary">Добавить клиента</button>
	</form>
</body>
</html>

LibraryApp/Views/Home/Index.cshtml
@{
	ViewBag.Title = "Home Page";
}

@model IEnumerable<LibraryApp.Models.Book>

<!DOCTYPE html>
<html>
<head>
	<link href="~/Content/Site.css" rel="stylesheet" />
	<title>Библиотека</title>
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
	<script>
        $(document).ready(function() {
            // Функция для редактирования описания
            $('.editDescription').click(function() {
                var row = $(this).closest('tr');
                var descriptionCell = row.find('.description');
                var description = descriptionCell.text().trim();
                var inputField = $('<input type="text" class="form-control descriptionInput" value="' + description + '">');
                descriptionCell.empty().append(inputField);
                $(this).hide();
                row.find('.saveDescription').show();
            });

            // Функция для сохранения измененного описания
            $('.saveDescription').click(function() {
                var row = $(this).closest('tr');
                var descriptionInput = row.find('.descriptionInput');
                var description = descriptionInput.val();
                var bookId = row.find('.bookId').text().trim();

                $.ajax({
                    url: '@Url.Action("UpdateBookDescription", "Home")',
                    type: 'POST',
                    data: { id: bookId, description: description },
                    success: function(response) {
                        if (response.success) {
                            // Обновление описания на странице
                            var descriptionCell = row.find('.description');
                            descriptionCell.text(description);
                            // Показать кнопку редактирования
                            row.find('.editDescription').show();
                            row.find('.saveDescription').hide();
                        } else {
                            alert("Ошибка: " + response.message);
                        }
                    },
                    error: function(xhr, status, error) {
                        console.error(error);
                        alert("При изменении описания произошла ошибка!");
                    }
                });
            });
            // Функция для аренды или возврата книги
            $('.rentOrReturnBook').click(function() {
				var row = $(this).closest('tr');
				var bookId = row.find('.bookId').text().trim();
                var isAvailable = row.find('.isAvailable');
				var booleanValue = JSON.parse(isAvailable.text().toLowerCase());;
				console.log("Current isAvailable: " + booleanValue);

				if (booleanValue) {
					var clientEmail = prompt("Пожалуйста, введите Email клиента:");

					if (!clientEmail) {
						alert("Вы не ввели Email!");
						return;
					}
                }

                $.ajax({
                    url: '@Url.Action("RentOrReturnBook", "Home")',
                    type: 'POST',
					data: { bookId: bookId, clientEmail: clientEmail, isAvailable: booleanValue },
                    success: function(response) {
                        if (response.success) {
                            // Обновление кнопки и состояния книги на странице
                            var button = row.find('.rentOrReturnBook');
							if (booleanValue) {
                                button.text('Возврат');
								isAvailable.text('False');
                            } else {
                                button.text('Аренда');
								isAvailable.text('True');
                            }
                        } else {
                            alert("Error: " + response.message);
                        }
                    },
                    error: function(xhr, status, error) {
                        console.error(error);
                        alert("При осуществлении аренды произошла ошибка!");
                    }
                });
            });
        });
	</script>
</head>
<body>
	<div>
		<h3>Библиотека</h3>
		<a href="@Url.Action("AddBook", "Book")" class="btn btn-primary">Добавить книгу</a>
		<a href="@Url.Action("AddClient", "Client")" class="btn btn-primary">Добавить клиента</a>
		<table id="booksTable">
			<thead>
				<tr>
					<th>Номер</th>
					<th>Название книги</th>
					<th>Автор</th>
                    <th>Состояние</th>
					<th>Описание</th>
					<th>Функциональные возможности</th>
				</tr>
			</thead>
			<tbody>
				@foreach (var book in Model)
				{
					<tr>
						<td class="bookId">@book.Id</td>
						<td>@book.Name</td>
						<td>@book.Author</td>
						<td class="isAvailable">@book.IsAvailable</td>
						<td class="description">@book.Description</td>
						<td>
							<button class="editDescription btn btn-primary">Изменить описание</button>
							<button class="saveDescription btn btn-success" style="display:none;">Сохранить</button>
							<button class="rentOrReturnBook btn btn-secondary" data-isavailable="@book.IsAvailable">
								@(book.IsAvailable ? "Аренда" : "Возврат")
							</button>
						</td>
					</tr>
				}
			</tbody>
		</table>
    </div>
</body>
</html>

LibraryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Библиотека", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Главная", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Добавить Книгу", "AddBook", "Book", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Добавить Клиента", "AddClient", "Client", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>